"""empty message

Revision ID: 14276c52a49c
Revises: 
Create Date: 2020-05-10 15:14:56.601142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14276c52a49c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_organisationfunder_table',
    sa.Column('organisationfunder_id', sa.Integer(), nullable=True),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.ForeignKeyConstraint(['organisationfunder_id'], ['organisationfunder.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_organisationfunder_table')
    # ### end Alembic commands ###
